import crypto from 'node:crypto';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
const MCP_URL='https://api.krea.ai/mcp',META_URL='https://www.krea.ai/.well-known/oauth-authorization-server',FLOW_COOKIE='__Host-krea_flow',TOKEN_COOKIE='__Host-krea_tokens';
const send=(res,status,body)=>{res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(body))};
const originFor=req=>`${req.headers['x-forwarded-proto']||'https'}://${req.headers['x-forwarded-host']||req.headers.host}`;
const parseCookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(p=>{const i=p.indexOf('=');return i<0?[p,'']:[p.slice(0,i),decodeURIComponent(p.slice(i+1))]}));
const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),decode=v=>{try{return v?JSON.parse(Buffer.from(v,'base64url').toString('utf8')):null}catch{return null}},cookie=(n,v,age=1800)=>`${n}=${encodeURIComponent(v)}; Path=/; Max-Age=${age}; SameSite=Lax; Secure; HttpOnly`,clear=n=>`${n}=; Path=/; Max-Age=0; SameSite=Lax; Secure; HttpOnly`,rand=n=>crypto.randomBytes(n).toString('base64url'),challenge=v=>crypto.createHash('sha256').update(v).digest('base64url');
async function body(req){const a=[];for await(const c of req)a.push(c);return a.length?JSON.parse(Buffer.concat(a).toString('utf8')):{}}
async function meta(){const r=await fetch(META_URL,{headers:{accept:'application/json'}});if(!r.ok)throw Error(`Krea OAuth discovery failed (${r.status})`);return r.json()}
async function start(req,res){const redirectUri=`${originFor(req)}/api?action=callback`,m=await meta(),rr=await fetch(m.registration_endpoint,{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({client_name:'Chatty Creator Studio — Krea Potato',client_uri:redirectUri.replace('/api?action=callback','/'),redirect_uris:[redirectUri],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none'})}),c=await rr.json();if(!rr.ok||!c.client_id)throw Error(`Krea client registration failed (${rr.status})`);const verifier=rand(48),state=rand(24),u=new URL(m.authorization_endpoint);for(const [k,v] of Object.entries({response_type:'code',client_id:c.client_id,redirect_uri:redirectUri,state,code_challenge:challenge(verifier),code_challenge_method:'S256',resource:MCP_URL}))u.searchParams.set(k,v);res.statusCode=302;res.setHeader('set-cookie',cookie(FLOW_COOKIE,encode({state,verifier,clientId:c.client_id,redirectUri}),600));res.setHeader('location',u);res.end()}
async function callback(req,res,u){const f=decode(parseCookies(req)[FLOW_COOKIE]),code=u.searchParams.get('code'),state=u.searchParams.get('state');if(u.searchParams.get('error'))throw Error(u.searchParams.get('error_description')||u.searchParams.get('error'));if(!f||!code||state!==f.state)throw Error('OAuth state validation failed');const m=await meta(),r=await fetch(m.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body:new URLSearchParams({grant_type:'authorization_code',code,client_id:f.clientId,redirect_uri:f.redirectUri,code_verifier:f.verifier,resource:MCP_URL})}),t=await r.json();if(!r.ok||!t.access_token)throw Error(`Krea token exchange failed (${r.status})`);const now=Math.floor(Date.now()/1000),stored={...t,client_id:f.clientId,expires_at:t.expires_in?now+Number(t.expires_in):null};res.statusCode=302;res.setHeader('set-cookie',[cookie(TOKEN_COOKIE,encode(stored),2592000),clear(FLOW_COOKIE)]);res.setHeader('location','/?connected=1');res.end()}
function stored(req){const s=decode(parseCookies(req)[TOKEN_COOKIE]);return s?.access_token?s:null}
async function token(req){const s=stored(req);if(!s)return{token:null};const now=Math.floor(Date.now()/1000);if(!s.expires_at||s.expires_at-now>90||!s.refresh_token)return{token:s.access_token};const m=await meta(),r=await fetch(m.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:s.refresh_token,client_id:s.client_id,resource:MCP_URL})}),n=await r.json();if(!r.ok||!n.access_token)return{token:null};const x={...s,...n,refresh_token:n.refresh_token||s.refresh_token,expires_at:n.expires_in?now+Number(n.expires_in):s.expires_at};return{token:x.access_token,cookie:cookie(TOKEN_COOKIE,encode(x),2592000)}}
async function krea(tok,fn){const c=new Client({name:'chatty-creator-studio-krea',version:'0.2.0'},{capabilities:{}}),tr=new StreamableHTTPClientTransport(new URL(MCP_URL),{requestInit:{headers:{Authorization:`Bearer ${tok}`}}});await c.connect(tr);try{return await fn(c)}finally{await c.close().catch(()=>{})}}
function payload(r){if(r?.structuredContent!=null)return r.structuredContent;const t=r?.content?.find?.(x=>x.type==='text')?.text;if(t){try{return JSON.parse(t)}catch{return{text:t}}}return r??{}}
function args(tool,b){const p=tool?.inputSchema?.properties||{},a={},input={prompt:b.prompt,...(b.options||{})};if('model'in p)a.model=b.model;else if('model_id'in p)a.model_id=b.model;else if('modelId'in p)a.modelId=b.model;if('input'in p)a.input=input;else Object.assign(a,input);if('sync'in p)a.sync=false;if('media_type'in p)a.media_type=b.kind;return a}
function jid(t,id){const p=t?.inputSchema?.properties||{};return 'jobId'in p?{jobId:id}:'job_id'in p?{job_id:id}:'id'in p?{id}:{jobId:id}}
export default async function handler(req,res){const u=new URL(req.url,'https://local'),action=u.searchParams.get('action')||'status';try{if(action==='start')return start(req,res);if(action==='callback')return callback(req,res,u);if(action==='disconnect'){res.setHeader('set-cookie',[clear(TOKEN_COOKIE),clear(FLOW_COOKIE)]);return send(res,200,{ok:true})}if(action==='status'){const s=stored(req);return send(res,200,{connected:!!s,expiresAt:s?.expires_at||null})}const a=await token(req);if(!a.token)return send(res,401,{error:'not_connected'});if(a.cookie)res.setHeader('set-cookie',a.cookie);if(action==='models'){const r=await krea(a.token,c=>c.callTool({name:'list_models',arguments:{}}));return send(res,200,payload(r))}if(action==='job'){const id=u.searchParams.get('id');if(!id)return send(res,400,{error:'id_required'});const r=await krea(a.token,async c=>{const l=await c.listTools(),t=(l.tools||[]).find(x=>x.name==='get_job');if(!t)throw Error('Krea get_job tool unavailable');return c.callTool({name:t.name,arguments:jid(t,id)})});return send(res,200,payload(r))}if(action==='generate'){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});const b=await body(req);if(!['image','video'].includes(b.kind)||!b.model||!b.prompt)return send(res,400,{error:'kind_model_prompt_required'});const d=await krea(a.token,async c=>{const l=await c.listTools(),names=b.kind==='video'?['generate_video','generate']:['generate_image','generate'],t=names.map(n=>(l.tools||[]).find(x=>x.name===n)).find(Boolean)||(l.tools||[]).find(x=>/generate/i.test(x.name)&&new RegExp(b.kind,'i').test(`${x.name} ${x.description||''}`));if(!t)throw Error(`No ${b.kind} generation tool exposed by Krea`);const r=await c.callTool({name:t.name,arguments:args(t,b)});return{tool:t.name,result:payload(r)}});return send(res,200,d)}return send(res,404,{error:'unknown_action'})}catch(e){if(action==='start'||action==='callback'){res.statusCode=302;res.setHeader('location',`/?auth_error=${encodeURIComponent(e.message)}`);return res.end()}return send(res,502,{error:e.message})}}
